-- Oracle 쿼리

-- flightspecial 테이블 삭제
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE flightspecial';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
END IF;
END;
/

-- flightspecial 테이블 생성
CREATE TABLE flightspecial (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               header VARCHAR2(255) DEFAULT '' NOT NULL,
                               body VARCHAR2(255),
                               origin VARCHAR2(255),
                               originCode VARCHAR2(6),
                               destination VARCHAR2(255),
                               destinationCode VARCHAR2(6),
                               cost NUMBER NOT NULL,
                               expiryDate NUMBER(16) NOT NULL
);

-- flightspecial 데이터 삽입
INSERT INTO flightspecial (expiryDate, cost, header, body, origin, originCode, destination, destinationCode)
VALUES (
           (SELECT (CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - DATE '1970-01-01') * 86400000 FROM DUAL) + 79200 + DBMS_RANDOM.VALUE(0, 20000000),
           50 + DBMS_RANDOM.VALUE(0, 200),
           'London to Prague',
           'Jewel of the East',
           'London',
           'LHR',
           'Paris',
           'CDG'
       );

-- hotelspecial 테이블 삭제
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE hotelspecial';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
END IF;
END;
/

-- hotelspecial 테이블 생성
CREATE TABLE hotelspecial (
                              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              hotel VARCHAR2(255) DEFAULT '' NOT NULL,
                              description VARCHAR2(255),
                              location VARCHAR2(255),
                              cost NUMBER NOT NULL,
                              expiryDate NUMBER(16) NOT NULL
);

-- hotelspecial 데이터 삽입
INSERT INTO hotelspecial (expiryDate, cost, hotel, description, location)
VALUES (
           (SELECT (CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - DATE '1970-01-01') * 86400000 FROM DUAL) + 79200 + DBMS_RANDOM.VALUE(0, 20000000),
           50 + DBMS_RANDOM.VALUE(0, 1000),
           'Sommerset Hotel',
           'Minimum stay 3 nights',
           'Sydney'
       );
