apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: general
spec:
  labels:
    cluster-name: ${cluster_name}
    workload-type/general: "true"
    billing: "aws-proserve"
  requirements:
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["c", "m", "r"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["4", "8", "16", "32"]
    - key: "karpenter.k8s.aws/instance-hypervisor"
      operator: In
      values: ["nitro"]
    - key: "karpenter.k8s.aws/instance-generation"
      operator: Gt
      values: ["4"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["on-demand"]
    # Disable taints for general purpose.
#  taints:
#    - key: workload-type/general
#      value: "true"
#      effect: NoSchedule
  limits:
    resources:
      cpu: 1k
      mem: 1000Gi
#  consolidation:
#    enabled: true
  providerRef:
    name: aws-node-template
  # expected exactly one, got both: spec.consolidation.enabled, spec.ttlSecondsAfterEmpty
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 7200
